version: '3.1'
services:
#-------------For Message Bus--------------- #
  redis:
    image: 'redis:latest'
    ports:
    - "1769:6379"
    environment:
      - appendonly=yes
    volumes:
            - redisdb:/var/lib/redis 
    restart: always

#-----------For Business DB, Event Store and Query DB----------------- #

  mongo:
    image: mongo
    restart: always
    ports:
            - 9269:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
            - mongodb:/data/db
#------------DB Exporer--------------------- #

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5269:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#-------------Persistent Volumes-------------------- #

volumes:
  mongodb:     
  redisdb:      